'use client'

import { useState } from 'react'
import { FileDown, Loader2 } from 'lucide-react'
import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'
import { useLang } from '@/contexts/LangContext'
import { toast } from 'sonner'

export default function ExportPDFButton({ targetId, fileName }: { targetId: string; fileName: string }) {
  const [loading, setLoading] = useState(false)
  const { lang } = useLang()

  async function handleExport() {
    const element = document.getElementById(targetId)
    if (!element) return

    setLoading(true)
    try {
      const canvas = await html2canvas(element, {
        scale: 2, // High quality
        useCORS: true,
        backgroundColor: '#F8FAFC', // Slate 50
        logging: false,
      })
      
      const imgData = canvas.toDataURL('image/png')
      const pdf = new jsPDF({
        orientation: 'portrait',
        unit: 'px',
        format: [canvas.width / 2, canvas.height / 2],
      })

      pdf.addImage(imgData, 'PNG', 0, 0, canvas.width / 2, canvas.height / 2)
      
      // Add a footer branding
      const footerY = (canvas.height / 2) - 10
      pdf.setFontSize(8)
      pdf.setTextColor(150)
      pdf.text('Generated by MacroDay AI - Your Everyday Nutrition Coach', 20, footerY)

      pdf.save(`${fileName}.pdf`)
      toast.success(lang === 'zh' ? 'PDF 導出成功！' : 'PDF Exported Successfully!')
    } catch (err) {
      console.error(err)
      toast.error(lang === 'zh' ? '導出失敗，請重試' : 'Export failed, please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <button
      onClick={handleExport}
      disabled={loading}
      className="flex items-center gap-2 px-3 py-1.5 text-xs font-bold bg-white text-slate-600 rounded-xl border border-slate-100 shadow-sm hover:border-[#0F9E75] hover:text-[#0F9E75] transition-all disabled:opacity-50"
    >
      {loading ? <Loader2 size={14} className="animate-spin" /> : <FileDown size={14} />}
      {lang === 'zh' ? '導出 PDF' : 'Export PDF'}
    </button>
  )
}
