import { PrismaClient, type Prisma } from '@prisma/client'
import type {
  CloudSnapshot,
  DailyMeals,
  InBodyRecord,
  MigrationPayload,
  PromptFeedbackInput,
  UserProfile,
  WeeklyPlan,
} from '@/lib/types'

const globalForPrisma = globalThis as unknown as { prisma?: PrismaClient }

export const prisma = globalForPrisma.prisma ?? new PrismaClient({ log: ['error'] })

if (process.env.NODE_ENV !== 'production') {
  globalForPrisma.prisma = prisma
}

export interface UpsertUserInput {
  email?: string | null
  name?: string | null
  image?: string | null
  provider: string
}

function asJson(value: unknown): Prisma.InputJsonValue {
  return value as Prisma.InputJsonValue
}

export async function upsertUser(input: UpsertUserInput) {
  if (!input.email) {
    return prisma.user.create({
      data: {
        email: null,
        name: input.name ?? undefined,
        image: input.image ?? undefined,
        provider: input.provider,
        lastLogin: new Date(),
      },
    })
  }

  return prisma.user.upsert({
    where: { email: input.email },
    update: {
      name: input.name ?? undefined,
      image: input.image ?? undefined,
      provider: input.provider,
      lastLogin: new Date(),
    },
    create: {
      email: input.email,
      name: input.name ?? undefined,
      image: input.image ?? undefined,
      provider: input.provider,
      lastLogin: new Date(),
    },
  })
}

export async function getUserByEmail(email: string) {
  return prisma.user.findUnique({ where: { email } })
}

export async function getUserById(id: string) {
  return prisma.user.findUnique({ where: { id } })
}

export async function getUserByStripeCustomerId(stripeCustomerId: string) {
  return prisma.user.findUnique({ where: { stripeCustomerId } })
}

export async function getUserByAuthAccount(provider: string, providerAccountId: string) {
  const account = await prisma.authAccount.findUnique({
    where: { provider_providerAccountId: { provider, providerAccountId } },
    include: { user: true },
  })
  return account?.user ?? null
}

export async function linkAuthAccountToUser(input: {
  userId: string
  provider: string
  providerAccountId: string
  email?: string | null
}) {
  return prisma.authAccount.upsert({
    where: {
      provider_providerAccountId: {
        provider: input.provider,
        providerAccountId: input.providerAccountId,
      },
    },
    update: {
      userId: input.userId,
      email: input.email ?? undefined,
    },
    create: {
      userId: input.userId,
      provider: input.provider,
      providerAccountId: input.providerAccountId,
      email: input.email ?? undefined,
    },
  })
}

export async function resolveOAuthUser(input: {
  provider: string
  providerAccountId: string
  email?: string | null
  name?: string | null
  image?: string | null
}) {
  const linked = await getUserByAuthAccount(input.provider, input.providerAccountId)
  if (linked) {
    return prisma.user.update({
      where: { id: linked.id },
      data: {
        email: linked.email ?? input.email ?? undefined,
        name: input.name ?? undefined,
        image: input.image ?? undefined,
        provider: input.provider,
        lastLogin: new Date(),
      },
    })
  }

  const normalizedEmail = input.email?.toLowerCase().trim() ?? null
  const existingByEmail = normalizedEmail ? await getUserByEmail(normalizedEmail) : null
  const user =
    existingByEmail ??
    (await upsertUser({
      email: normalizedEmail,
      name: input.name,
      image: input.image,
      provider: input.provider,
    }))

  await linkAuthAccountToUser({
    userId: user.id,
    provider: input.provider,
    providerAccountId: input.providerAccountId,
    email: normalizedEmail,
  })

  return user
}

export async function getAutoGenerateUsers() {
  return prisma.user.findMany({
    where: { 
      autoGenerateDaily: true,
      isPro: true 
    }
  })
}

export async function getLatestInBodyRecord(userId: string) {
  // The user's OWN latest measurement (exclude client/student entries).
  return prisma.inBodyEntry.findFirst({
    where: { userId, clientId: null },
    orderBy: { createdAt: 'desc' }
  })
}

export async function setUserProStatus(userId: string, isPro: boolean, proTrialEndsAt?: Date | null) {
  return prisma.user.update({
    where: { id: userId },
    data: {
      isPro,
      proTrialEndsAt: proTrialEndsAt ?? undefined,
    },
  })
}

export async function setUserAdFreeStatus(userId: string, isAdFree: boolean) {
  return prisma.user.update({
    where: { id: userId },
    data: { isAdFree },
  })
}

export async function updateUserAutoGenerate(userId: string, enabled: boolean) {
  return prisma.user.update({
    where: { id: userId },
    data: { autoGenerateDaily: enabled }
  })
}

export async function syncUserLocalData(userId: string, payload: MigrationPayload) {
  const updateUser: Prisma.UserUpdateInput = {}
  const profile = payload.profile

  if (profile) {
    updateUser.preferredCuisine = profile.preferredCuisine ?? null
    updateUser.dietaryRestrictions = asJson(profile.dietaryRestrictions ?? [])
    updateUser.dislikedIngredients = asJson(profile.dislikedIngredients ?? [])
    if (typeof profile.isPro === 'boolean') {
      updateUser.isPro = profile.isPro
    }
    if (typeof profile.isAdFree === 'boolean') {
      updateUser.isAdFree = profile.isAdFree
    }
    // New: Sync autoGenerateDaily if present
    if (typeof (profile as any).autoGenerateDaily === 'boolean') {
      updateUser.autoGenerateDaily = (profile as any).autoGenerateDaily
    }
    // New: Sync goal
    if (profile.goal) {
      updateUser.goal = profile.goal
    }

    updateUser.streak = payload.currentStreak ?? 0
  }

  if (payload.appState) {
    updateUser.localState = asJson(payload.appState)
  }

  if (Object.keys(updateUser).length > 0) {
    await prisma.user.update({
      where: { id: userId },
      data: updateUser,
    })
  }

  if (payload.inbodyHistory.length > 0) {
    // Dedupe incoming records: keep one per entryDate (last wins), and preserve
    // each record's id. Preserving the id is critical — the client merges cloud
    // + local InBody by id, so if the server regenerates ids on every sync the
    // records never match and duplicate exponentially.
    const byDate = new Map<string, InBodyRecord>()
    for (const record of payload.inbodyHistory) {
      byDate.set(record.date, record)
    }
    const deduped = Array.from(byDate.values())

    // Only replace the user's OWN measurements (clientId = null). Client/student
    // entries share this userId (the coach) but carry a clientId — they must NOT
    // be wiped by the coach's personal localStorage sync.
    await prisma.inBodyEntry.deleteMany({ where: { userId, clientId: null } })
    await prisma.inBodyEntry.createMany({
      data: deduped.map((record) => ({
        id: record.id || undefined, // preserve client id so merges stay stable
        userId,
        clientId: null,
        entryDate: record.date,
        weight: record.weight,
        height: record.height,
        gender: record.gender,
        age: record.age,
        bodyFat: record.bodyFat,
        skeletalMuscleMass: record.skeletalMuscleMass,
        bmr: record.bmr,
        visceralFatLevel: record.visceralFatLevel,
        bodyWater: record.bodyWater,
      })),
    })
  }

  const mealPlans: Array<Promise<unknown>> = []

  if (payload.dailyMeals) {
    mealPlans.push(
      prisma.mealPlan.upsert({
        where: {
          id: `daily_${userId}_${payload.dailyMeals.date}`,
        },
        update: {
          payload: asJson(payload.dailyMeals),
          targetCalories: payload.dailyMeals.targetCalories,
          targetProtein: payload.dailyMeals.targetProtein,
          promptVersion: payload.promptVersion ?? 'v2-regional',
          preferredCuisine: profile?.preferredCuisine ?? null,
          source: 'local-migration',
          planType: 'daily',
          planDate: payload.dailyMeals.date,
        },
        create: {
          id: `daily_${userId}_${payload.dailyMeals.date}`,
          userId,
          planType: 'daily',
          planDate: payload.dailyMeals.date,
          payload: asJson(payload.dailyMeals),
          targetCalories: payload.dailyMeals.targetCalories,
          targetProtein: payload.dailyMeals.targetProtein,
          promptVersion: payload.promptVersion ?? 'v2-regional',
          preferredCuisine: profile?.preferredCuisine ?? null,
          source: 'local-migration',
        },
      })
    )
  }

  if (payload.weeklyPlan) {
    mealPlans.push(
      prisma.mealPlan.upsert({
        where: { id: payload.weeklyPlan.id },
        update: {
          payload: asJson(payload.weeklyPlan),
          targetCalories: payload.weeklyPlan.targetCalories,
          targetProtein: payload.weeklyPlan.targetProtein,
          promptVersion: payload.promptVersion ?? 'v2-regional',
          preferredCuisine: profile?.preferredCuisine ?? null,
          source: 'local-migration',
          planType: 'weekly',
          weekStart: payload.weeklyPlan.days[0]?.date ?? null,
        },
        create: {
          id: payload.weeklyPlan.id,
          userId,
          planType: 'weekly',
          weekStart: payload.weeklyPlan.days[0]?.date ?? null,
          payload: asJson(payload.weeklyPlan),
          targetCalories: payload.weeklyPlan.targetCalories,
          targetProtein: payload.weeklyPlan.targetProtein,
          promptVersion: payload.promptVersion ?? 'v2-regional',
          preferredCuisine: profile?.preferredCuisine ?? null,
          source: 'local-migration',
        },
      })
    )
  }

  await Promise.all(mealPlans)
}

export async function getUserCloudSnapshot(userId: string): Promise<CloudSnapshot | null> {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    include: {
      // Only the user's own measurements — client/student entries (clientId set)
      // must not sync down into the coach's personal localStorage history.
      inbodyHistory: { where: { clientId: null }, orderBy: { createdAt: 'asc' } },
      mealPlans: {
        where: { OR: [{ planType: 'daily' }, { planType: 'weekly' }] },
        orderBy: { createdAt: 'desc' },
      },
    },
  })

  if (!user) return null

  const latestDaily = user.mealPlans.find((plan) => plan.planType === 'daily')?.payload as DailyMeals | undefined
  const latestWeekly = user.mealPlans.find((plan) => plan.planType === 'weekly')?.payload as WeeklyPlan | undefined
  const localState = (user.localState ?? {}) as Partial<MigrationPayload['appState']>

  return {
    profile: {
      goal: (user.goal as UserProfile['goal']) ?? 'maintain',
      activityLevel: 'moderate',
      fitnessLevel: 'beginner',
      dietaryRestrictions: (user.dietaryRestrictions as string[]) ?? [],
      proteinPreferences: [],
      carbPreferences: [],
      cuisinePreferences: [],
      preferredCuisine: (user.preferredCuisine as UserProfile['preferredCuisine']) ?? undefined,
      dislikedIngredients: (user.dislikedIngredients as string[]) ?? [],
      cookingStyle: 'both',
      isPro: user.isPro,
      isAdFree: user.isAdFree,
      autoGenerateDaily: user.autoGenerateDaily,
    },
    inbodyHistory: user.inbodyHistory.map((record) => ({
      id: record.id,
      date: record.entryDate,
      weight: record.weight,
      height: record.height,
      gender: record.gender as 'male' | 'female',
      age: record.age,
      bodyFat: record.bodyFat ?? undefined,
      skeletalMuscleMass: record.skeletalMuscleMass ?? undefined,
      bmr: record.bmr ?? undefined,
      visceralFatLevel: record.visceralFatLevel ?? undefined,
      bodyWater: record.bodyWater ?? undefined,
    })),
    dailyMeals: latestDaily ?? null,
    weeklyPlan: latestWeekly ?? null,
    currentStreak: user.streak,
    appState: {
      trainingHistory: localState?.trainingHistory ?? [],
      favorites: localState?.favorites ?? [],
      lang: localState?.lang === 'en' ? 'en' : 'zh',
      eatenMeals: localState?.eatenMeals ?? {},
    },
  }
}

export async function saveGeneratedDailyPlan(userId: string, plan: DailyMeals, profile: UserProfile, promptVersion: string) {
  await prisma.mealPlan.upsert({
    where: { id: `daily_${userId}_${plan.date}` },
    update: {
      payload: asJson(plan),
      targetCalories: plan.targetCalories,
      targetProtein: plan.targetProtein,
      promptVersion,
      preferredCuisine: profile.preferredCuisine ?? null,
      source: 'ai',
      planType: 'daily',
      planDate: plan.date,
    },
    create: {
      id: `daily_${userId}_${plan.date}`,
      userId,
      planType: 'daily',
      planDate: plan.date,
      payload: asJson(plan),
      targetCalories: plan.targetCalories,
      targetProtein: plan.targetProtein,
      promptVersion,
      preferredCuisine: profile.preferredCuisine ?? null,
      source: 'ai',
    },
  })
}

export async function saveGeneratedWeeklyPlan(userId: string, plan: WeeklyPlan, profile: UserProfile, promptVersion: string) {
  await prisma.mealPlan.upsert({
    where: { id: plan.id },
    update: {
      payload: asJson(plan),
      targetCalories: plan.targetCalories,
      targetProtein: plan.targetProtein,
      promptVersion,
      preferredCuisine: profile.preferredCuisine ?? null,
      source: 'ai',
      planType: 'weekly',
      weekStart: plan.days[0]?.date ?? null,
    },
    create: {
      id: plan.id,
      userId,
      planType: 'weekly',
      weekStart: plan.days[0]?.date ?? null,
      payload: asJson(plan),
      targetCalories: plan.targetCalories,
      targetProtein: plan.targetProtein,
      promptVersion,
      preferredCuisine: profile.preferredCuisine ?? null,
      source: 'ai',
    },
  })
}

export async function savePromptFeedback(userId: string, input: PromptFeedbackInput) {
  return prisma.promptFeedback.create({
    data: {
      userId,
      mealPlanId: input.mealPlanId ?? undefined,
      mealType: input.mealType ?? undefined,
      reason: input.reason ?? undefined,
      dislikedIngredients: asJson(input.dislikedIngredients ?? []),
      promptVersion: input.promptVersion,
    },
  })
}

export async function listForumPosts(
  currentUserId?: string,
  filter: 'hot' | 'mine' | 'following' = 'hot'
) {
  const where: Prisma.ForumPostWhereInput =
    filter === 'mine' && currentUserId ? { userId: currentUserId } : {}

  const orderBy =
    filter === 'hot'
      ? [{ likesCount: 'desc' as const }, { createdAt: 'desc' as const }]
      : [{ createdAt: 'desc' as const }]

  const posts = await prisma.forumPost.findMany({
    where,
    orderBy,
    take: 30,
    include: {
      user: true,
      replies: {
        orderBy: { createdAt: 'asc' },
        include: { user: true },
        take: 8,
      },
      likes: currentUserId
        ? {
            where: { userId: currentUserId },
            select: { id: true },
          }
        : false,
    },
  })

  return posts.map((post) => ({
    ...post,
    likedByMe: Array.isArray(post.likes) ? post.likes.length > 0 : false,
  }))
}

export async function createForumPost(args: {
  userId: string
  content: string
  mealImage?: string | null
  compliance?: number | null
  streakSnapshot?: number | null
  isCheckIn?: boolean
}) {
  return prisma.forumPost.create({
    data: {
      userId: args.userId,
      content: args.content,
      mealImage: args.mealImage ?? undefined,
      compliance: args.compliance ?? undefined,
      streakSnapshot: args.streakSnapshot ?? undefined,
      isCheckIn: args.isCheckIn ?? false,
    },
  })
}

export async function toggleForumLike(postId: string, userId: string) {
  const existing = await prisma.forumLike.findUnique({
    where: { postId_userId: { postId, userId } },
  })

  if (existing) {
    await prisma.$transaction([
      prisma.forumLike.delete({ where: { postId_userId: { postId, userId } } }),
      prisma.forumPost.update({
        where: { id: postId },
        data: { likesCount: { decrement: 1 } },
      }),
    ])
    return { liked: false }
  }

  await prisma.$transaction([
    prisma.forumLike.create({ data: { postId, userId } }),
    prisma.forumPost.update({
      where: { id: postId },
      data: { likesCount: { increment: 1 } },
    }),
  ])
  return { liked: true }
}

export async function createForumReply(postId: string, userId: string, content: string) {
  const reply = await prisma.forumReply.create({
    data: { postId, userId, content },
    include: { user: true },
  })

  await prisma.forumPost.update({
    where: { id: postId },
    data: { replyCount: { increment: 1 } },
  })

  return reply
}

export async function getForumPost(postId: string, currentUserId?: string) {
  const post = await prisma.forumPost.findUnique({
    where: { id: postId },
    include: {
      user: true,
      replies: {
        orderBy: { createdAt: 'asc' },
        include: { user: true },
      },
      likes: currentUserId
        ? {
            where: { userId: currentUserId },
            select: { id: true },
          }
        : false,
    },
  })

  if (!post) return null

  return {
    ...post,
    likedByMe: Array.isArray(post.likes) ? post.likes.length > 0 : false,
  }
}

// Subscription Management Functions

export async function setUserSubscription(userId: string, data: {
  stripeCustomerId?: string
  stripeSubscriptionId?: string
  subscriptionStatus?: string
  isPro?: boolean
  isAdFree?: boolean
  proTrialEndsAt?: Date | null
}) {
  return prisma.user.update({
    where: { id: userId },
    data: {
      stripeCustomerId: data.stripeCustomerId,
      stripeSubscriptionId: data.stripeSubscriptionId,
      subscriptionStatus: data.subscriptionStatus,
      isPro: data.isPro,
      isAdFree: data.isAdFree,
      proTrialEndsAt: data.proTrialEndsAt,
    },
  })
}

export async function getSubscriptionStatus(userId: string) {
  return prisma.user.findUnique({
    where: { id: userId },
    select: {
      stripeCustomerId: true,
      stripeSubscriptionId: true,
      subscriptionStatus: true,
      isPro: true,
      isAdFree: true,
      proTrialEndsAt: true,
    },
  })
}

export async function logSubscriptionHistory(userId: string, fromPlan: string, toPlan: string, stripeEventId?: string) {
  return prisma.subscriptionHistory.create({
    data: {
      userId,
      fromPlan,
      toPlan,
      stripeEventId,
    },
  })
}

export async function createInvoice(data: {
  userId: string
  stripeInvoiceId: string
  amount: number
  currency: string
  status: string
  dueDate?: Date | null
  paidAt?: Date | null
  description?: string | null
}) {
  return prisma.invoice.create({
    data,
  })
}

export async function getSubscriptionInvoices(userId: string, limit: number = 20) {
  return prisma.invoice.findMany({
    where: { userId },
    orderBy: { createdAt: 'desc' },
    take: limit,
  })
}

export async function updateInvoiceStatus(stripeInvoiceId: string, status: string, paidAt?: Date) {
  return prisma.invoice.update({
    where: { stripeInvoiceId },
    data: {
      status,
      paidAt,
    },
  })
}

// ---------------------------------------------------------------------------
// Coach → Clients (PT InBody hub). coachId is always the logged-in User. Every
// read/write verifies the client belongs to the caller to prevent one coach
// from touching another coach's clients (IDOR).
// ---------------------------------------------------------------------------

export interface ClientInput {
  name: string
  contact?: string | null
  gender?: string | null
  notes?: string | null
}

// Measurement fields written for a client's InBody entry (from OCR + coach edit).
export interface ClientInBodyInput {
  entryDate: string
  weight: number
  height: number
  gender: string
  age: number
  bodyFat?: number | null
  skeletalMuscleMass?: number | null
  bmr?: number | null
  visceralFatLevel?: number | null
  visceralFatArea?: number | null
  bodyWater?: number | null
  inbodyScore?: number | null
  bmi?: number | null
}

export async function listClients(coachId: string) {
  return prisma.client.findMany({
    where: { coachId },
    orderBy: { createdAt: 'asc' },
    include: {
      inbodyEntries: {
        orderBy: { entryDate: 'desc' },
        take: 1, // latest measurement for the list thumbnail
      },
    },
  })
}

export async function createClient(coachId: string, input: ClientInput) {
  return prisma.client.create({
    data: {
      coachId,
      name: input.name.trim().slice(0, 60),
      contact: input.contact?.trim().slice(0, 120) || null,
      gender: input.gender || null,
      notes: input.notes?.trim().slice(0, 500) || null,
    },
  })
}

export async function updateClient(coachId: string, clientId: string, input: Partial<ClientInput>) {
  // Scope the update by coachId so a foreign clientId simply updates nothing.
  const res = await prisma.client.updateMany({
    where: { id: clientId, coachId },
    data: {
      ...(input.name !== undefined ? { name: input.name.trim().slice(0, 60) } : {}),
      ...(input.contact !== undefined ? { contact: input.contact?.trim().slice(0, 120) || null } : {}),
      ...(input.gender !== undefined ? { gender: input.gender || null } : {}),
      ...(input.notes !== undefined ? { notes: input.notes?.trim().slice(0, 500) || null } : {}),
    },
  })
  return res.count > 0
}

export async function deleteClient(coachId: string, clientId: string) {
  const res = await prisma.client.deleteMany({ where: { id: clientId, coachId } })
  return res.count > 0
}

// Returns the client's InBody history, or null if the client is not the caller's.
export async function getClientInBody(coachId: string, clientId: string) {
  const client = await prisma.client.findFirst({ where: { id: clientId, coachId } })
  if (!client) return null
  const entries = await prisma.inBodyEntry.findMany({
    where: { clientId },
    orderBy: { entryDate: 'asc' },
  })
  return { client, entries }
}

// Adds a measurement to a client the caller owns. Returns the row, or null if
// the client is not theirs.
export async function addClientInBodyEntry(coachId: string, clientId: string, input: ClientInBodyInput) {
  const client = await prisma.client.findFirst({ where: { id: clientId, coachId } })
  if (!client) return null
  return prisma.inBodyEntry.create({
    data: {
      userId: coachId,
      clientId,
      entryDate: input.entryDate,
      weight: input.weight,
      height: input.height,
      gender: input.gender,
      age: input.age,
      bodyFat: input.bodyFat ?? null,
      skeletalMuscleMass: input.skeletalMuscleMass ?? null,
      bmr: input.bmr ?? null,
      visceralFatLevel: input.visceralFatLevel ?? null,
      visceralFatArea: input.visceralFatArea ?? null,
      bodyWater: input.bodyWater ?? null,
      inbodyScore: input.inbodyScore ?? null,
      bmi: input.bmi ?? null,
    },
  })
}

export async function deleteClientInBodyEntry(coachId: string, clientId: string, entryId: string) {
  // entryId must belong to a client owned by the caller.
  const client = await prisma.client.findFirst({ where: { id: clientId, coachId } })
  if (!client) return false
  const res = await prisma.inBodyEntry.deleteMany({ where: { id: entryId, clientId } })
  return res.count > 0
}
