export type PreferredCuisine =
  | 'Argentine'
  | 'Latin American'
  | 'Mediterranean'
  | 'Asian'
  | 'High Protein Classics'

export interface InBodyRecord {
  id: string
  date: string
  weight: number
  height: number
  gender: 'male' | 'female'
  age: number
  bodyFat?: number
  skeletalMuscleMass?: number
  bmr?: number
  visceralFatLevel?: number
  bodyWater?: number
}

export interface UserProfile {
  goal: 'muscle_gain' | 'fat_loss' | 'maintain'
  fitnessLevel?: 'beginner' | 'active' | 'advanced'
  dietaryRestrictions: string[]
  proteinPreferences: string[]
  carbPreferences: string[]
  cuisinePreferences: string[]
  preferredCuisine?: PreferredCuisine
  dislikedIngredients?: string[]
  cookingStyle: 'home' | 'takeout' | 'both'
  weeklyBudget?: number
  isPro: boolean
  isAdFree: boolean
  autoGenerateDaily?: boolean
}


export interface Meal {
  name: string
  cookingTime: number
  calories: number
  protein: number
  carbs: number
  fat: number
  ingredients: string[]
  steps: string[]
  isTakeout?: boolean
  whereToGet?: string
  imageUrl?: string
  imagePrompt?: string
  isEaten?: boolean
}

export interface DailyMeals {
  date: string
  breakfast: Meal
  lunch: Meal
  dinner: Meal
  targetCalories: number
  targetProtein: number
  promptVersion?: string
  coachOpinion?: string
}

export interface DayPlan {
  date: string
  breakfast: Meal
  lunch: Meal
  dinner: Meal
  snack?: Meal
  totalCalories: number
  totalProtein: number
  totalCarbs: number
  totalFat: number
  coachOpinion?: string
}

export interface WeeklyPlan {
  id: string
  createdAt: string
  days: DayPlan[]
  shoppingList: ShoppingItem[]
  targetCalories: number
  targetProtein: number
  promptVersion?: string
}

export interface ShoppingItem {
  name: string
  amount: string
  category: 'protein' | 'vegetables' | 'carbs' | 'dairy' | 'condiments' | 'other'
}

export interface UsageRecord {
  date: string
  count: number
  adRewards?: number
}

export interface GuestSession {
  id: string
  isGuest: boolean
  createdAt: string
}

export interface MigrationPayload {
  inbodyHistory: InBodyRecord[]
  profile: UserProfile | null
  dailyMeals: DailyMeals | null
  weeklyPlan: WeeklyPlan | null
  currentStreak: number
  promptVersion?: string
}

export interface PromptFeedbackInput {
  mealPlanId?: string
  mealType?: 'breakfast' | 'lunch' | 'dinner'
  reason?: string
  dislikedIngredients?: string[]
  promptVersion: string
}

export interface ForumReplyItem {
  id: string
  content: string
  createdAt: string
  user: {
    id: string
    name?: string | null
    image?: string | null
    email?: string | null
  }
}

export interface ForumPostItem {
  id: string
  content: string
  mealImage?: string | null
  compliance?: number | null
  streakSnapshot?: number | null
  isCheckIn: boolean
  likesCount: number
  replyCount: number
  likedByMe: boolean
  createdAt: string
  user: {
    id: string
    name?: string | null
    image?: string | null
    email?: string | null
  }
  replies: ForumReplyItem[]
}

export interface Exercise {
  name: string
  sets: number
  reps: string
  rest: string
  tips: string
}

export interface TrainingPlan {
  name: string
  duration: number
  warmup: string
  exercises: Exercise[]
  cooldown: string
  estimatedCalories: number
  notes: string
}

export interface TrainingRecord {
  date: string
  plan: TrainingPlan
  completed: boolean
  completedAt?: string
}
