import { NextRequest, NextResponse } from 'next/server'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/lib/auth'
import { prisma } from '@/lib/db'

export async function PATCH(req: NextRequest) {
  try {
    const session = await getServerSession(authOptions)
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    const body = await req.json()
    const { autoGenerateDaily, goal, preferredCuisine } = body

    const data: any = {}
    if (typeof autoGenerateDaily === 'boolean') data.autoGenerateDaily = autoGenerateDaily
    if (goal) data.goal = goal
    if (preferredCuisine) data.preferredCuisine = preferredCuisine

    const updated = await prisma.user.update({
      where: { id: session.user.id },
      data
    })

    return NextResponse.json(updated)
  } catch (err) {
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
